name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        go-version:
          - 1.13.x
          - 1.14.x
          - 1.15.x

    runs-on: ${{ matrix.os }}

    env:
      GO111MODULE: "on"
      GOPROXY: https://proxy.golang.org
      GORACE: halt_on_error=1
      
    steps:

    - name: Set up Go version ${{ matrix.go-version }}
      uses: actions/setup-go@v2.1.2
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: make test
